name: EmoteSlapper
main: emoteslapper\Main
version: 1.0.0
author: xStrixU
api: 3.14.0
mcpe-protocol: 440

permissions:
 emoteslapper.command:
   default: op
   description: Allow to use emoteslapper command
